# EuRoC All-Dataset Spectrograms

Run the same basis fit over every merged EuRoC CSV and display the average spectra plus coefficient spectrogram for each dataset. This notebook is deliberately noninteractive; edit the constants in the setup cell to change basis, `N`, interval length, or signal group. Supported basis values are `chebyshev`, `chebyshev2`, and `fourier`.

The initial hardcoded signal is `gyro`.

In [1]:
from __future__ import annotations

import sys
from pathlib import Path

from IPython.display import display

REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "python" / "imuFactors").exists():
    REPO_ROOT = Path("/Users/dellaert/git/imuFactors")

PYTHON_DIR = REPO_ROOT / "python"
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

import imuFactors.euroc as euroc
import imuFactors.spectral as spectral
import imuFactors.spectrogram as spectrogram

DATA_DIR = REPO_ROOT / "data" / "euroc"
DATA_FILES = euroc.discover_euroc_files(DATA_DIR)
if not DATA_FILES:
    raise FileNotFoundError(f"No EuRoC CSV files found in {DATA_DIR}")

SIGNAL_GROUP = "gyro"
BASIS = "chebyshev"
N = 14
WINDOW_SECONDS = 1.0
PART_COUNT = 4

print(f"Found {len(DATA_FILES)} EuRoC CSV files in {DATA_DIR}")
print(
    f"signal={SIGNAL_GROUP}, basis={BASIS}, "
    f"N={N}, interval={WINDOW_SECONDS:g}s"
)

Found 11 EuRoC CSV files in /Users/dellaert/git/imuFactors/data/euroc
signal=gyro, basis=chebyshev, N=14, interval=1s

In [2]:
results = {}
for path in DATA_FILES:
    dataset = path.stem.removeprefix("euroc_")
    print(f"fitting {dataset}...")
    results[dataset] = spectrogram.fit_spectral_windows(
        path,
        N=N,
        basis=BASIS,
        signal_group=SIGNAL_GROUP,
        window_seconds=WINDOW_SECONDS,
    )

print(f"fit {len(results)} datasets")

fitting MH01...
fitting MH02...
fitting MH03...
fitting MH04...
fitting MH05...
fitting V101...
fitting V102...
fitting V103...
fitting V201...
fitting V202...
fitting V203...
fit 11 datasets

## Average Spectra and Coefficient Spectrograms

Each dataset is shown with a summary table, its average spectra, and its `window_count x N` coefficient spectrogram. The spectrogram time axis is reversed so time 0 appears at the top.

In [3]:
for dataset, result in results.items():
    display(spectrogram.summary_table(result))

    average_figure = spectrogram.plot_average_spectra(
        result,
        part_count=PART_COUNT,
    )
    average_figure.update_layout(
        title=(
            f"{dataset}: {SIGNAL_GROUP} average spectra "
            f"({result.basis_name}, N={result.N}, "
            f"{result.window_seconds:g}s intervals)"
        )
    )
    average_figure.show()

    spectrogram_figure = spectrogram.plot_coefficient_spectrogram(result)
    spectrogram_figure.update_layout(
        title=(
            f"{dataset}: {SIGNAL_GROUP} coefficient spectrogram "
            f"({result.basis_name}, N={result.N}, "
            f"{result.window_seconds:g}s intervals)"
        )
    )
    spectrogram_figure.show()

                       quantity           value
0                          file  euroc_MH01.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             144
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         144.125

                       quantity           value
0                          file  euroc_MH02.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             113
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         113.635

                       quantity           value
0                          file  euroc_MH03.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             114
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration          114.43

                       quantity           value
0                          file  euroc_MH04.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals              79
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration          79.895

                       quantity           value
0                          file  euroc_MH05.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals              92
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration          92.895

                       quantity           value
0                          file  euroc_V101.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             139
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration          139.35

                       quantity           value
0                          file  euroc_V102.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals              80
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration           80.04

                       quantity           value
0                          file  euroc_V103.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             101
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         101.745

                       quantity           value
0                          file  euroc_V201.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             105
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         105.155

                       quantity           value
0                          file  euroc_V202.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             111
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         111.805

                       quantity           value
0                          file  euroc_V203.csv
1                         basis       Chebyshev
2              selected columns   w_x, w_y, w_z
3                             N              14
4                             n              13
5                   basis order       degree 13
6            lambda1 p' penalty             0.0
7           interval length [s]             1.0
8            complete intervals             108
9   m samples per closed window             201
10                    median dt           0.005
11               effective rate      199.995422
12                file duration         108.655

## All-Dataset Whole-File Average Comparison

This final heatmap compares the entire-file average coefficient spectrogram for every dataset. Each row is one dataset; each column is one spectral coefficient.

In [4]:
comparison_figure = spectrogram.plot_dataset_average_spectrograms(results)
comparison_figure.update_layout(
    title=(
        f"All datasets: {SIGNAL_GROUP} whole-file average coefficient spectrograms "
        f"({BASIS}, N={N}, {WINDOW_SECONDS:g}s intervals)"
    )
)
comparison_figure.show()